# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
      - "javascript"
      - "skip-release"
    schedule:
      interval: "quarterly"
    groups:
      patch_minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "actions"
      - "skip-release"
    schedule:
      interval: "quarterly"
