name: Release

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v6

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-json.lock') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-json.lock') }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run build
          npx auto shipit
